modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0-or-later"
issueTrackerURL = "https://github.com/quat1024/AutoThirdPerson/issues"
logoFile = "auto_third_person_64x.png"

[[mods]]
modId = "auto_third_person"
version = "${version}"
displayName = "Auto Third Person"
description = "Puts you in third person when you like, get in a boat and stuff."
authors = "quaternary"
credits = "Your mom"