name: the real

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/wrapper-validation-action@v1

      - uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: clean build

      - run: ./collect.sh

      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: collect